### ISSUE TITLE
Events when sticky is active

### ISSUE THREAD

**Issue by Shoekrates** [senff/Sticky-Anything#2]
Hi! Nice plugin, works like a charme.
Are there any plans to add events when "sticky" condition is reached? I want to make an element visible as soon as "sticky" is active.

**Comment by senff** [comment]
I didn't have any plans for building that in the plugin really, but it's fairly easy to customize. If you need help, hit me up through my site at www.senff.com and I'd be happy to help.

**Comment by Shoekrates** [comment]
OK, thanks. I found a way via .cloned class to set up a conditional state. That should do it for now.
