### ISSUE TITLE
The Mystery of the Expanding Menu Box

### ISSUE THREAD

**Issue by DanSGraham** [senff/Sticky-Anything#3]
This is a great piece of code, but I have noticed something strange. When I use the .min.js everything works as expected, however when I use the .js file included on this repo, the menu element I want to sticky (it does not take up the whole width) widens continually, even past the page width. I am not sure if this is a problem on my end or with the plugin, but I figured since it works fine with the .min maybe the most recent update created this bug? Thanks again for this amazing plugin!

**Comment by senff** [comment]
Indeed that's not supposed to happen. Would you be able to share your site so I can see what might be the cause?

**Comment by DanSGraham** [comment]
I can't give you access to my site because it isn't live yet. I made an example demo but I don't know how best to give you the html and css.

**Comment by senff** [comment]
Hey Dan, I replied to your email. If you want me to send some files, please go ahead!

**Comment by DanSGraham** [comment]
I thought I replied a while ago, but I just sent a follow up email. Let me know if you still haven't received that.

**Comment by senff** [comment]
Got it!

**Comment by Murilirum** [comment]
For future reference.

> I can't give you access to my site because it isn't live yet. I made an example demo but I don't know how best to give you the html and css.

A really good option is to use [Codepen](http://codepen.io/). I'm assuming this is resolved but figured a small tidbit of information could be helpful for the future.
