### ISSUE TITLE
Repeating Issue

### ISSUE THREAD

**Issue by MrJoshFisher** [senff/Sticky-Anything#4]
Hello, 

I'm having some issues with the sticky header and was wondering if you could assist, it maybe very simple when I scroll down the manu slides up when I scroll down to reveal a copy of itsself and as you scroll down its scrolls up its confusing. 
![screen shot 2015-09-29 at 1 16 07 pm](https://cloud.githubusercontent.com/assets/8970358/10163670/63e3933a-66ac-11e5-8bb5-0b2305c54549.png)

this is what i'm working from.

	<script type="text/javascript">
		// Create a clone of the menu, right next to original.
			$('.custom_menu').addClass('original').clone().insertAfter('.custom_menu').addClass('cloned').css('position','fixed').css('top','0').css('margin-top','0').css('z-index','500').removeClass('original').hide();
			
			scrollIntervalID = setInterval(stickIt, 700);
			
			
			function stickIt() {
			
			  var orgElementPos = $('.original').offset();
			  orgElementTop = orgElementPos.top;               
			
			  if ($(window).scrollTop() >= (orgElementTop)) {
			    // scrolled past the original position; now only show the cloned, sticky element.
			
			    // Cloned element should always have same left position and width as original element.     
			    orgElement = $('.original');
			    coordsOrgElement = orgElement.offset();
			    leftOrgElement = coordsOrgElement.left;  
			    widthOrgElement = orgElement.css('width');
			    $('.cloned').css('left',leftOrgElement+'px').css('top',0).css('width',widthOrgElement).show();
			    $('.original').css('visibility','hidden');
			  } else {
			    // not scrolled past the menu; only show the original menu.
			    $('.cloned').hide();
			    $('.original').css('visibility','visible');
			  }
			}
					
	</script>

**Comment by senff** [comment]
A little hard to tell from just a screenshot and example code. Would you be able to share a link to your site so I can see it for myself and investigate?

**Comment by MrJoshFisher** [comment]
hello yeh course its http://directkitchens.wp.castus1.co.uk/ 
castus / design

**Comment by senff** [comment]
It's strange, cause the plugin DOES add "visibility: hidden" to the original element (as it's supposed to do), yet it doesn't really apply in the browser -- it's still visible?!

Then only after I change some styles in the browser inspector, it actually becomes invisible. Same with the cloned item: additional styles are only applied when I actually *change* them in the inspector, but not right away.

Wondering if there is some JS sorcery involved....?

**Comment by MrJoshFisher** [comment]
Is there a quick fix that can be applied in the css or js?

**Comment by senff** [comment]
I'm thinking it's (related to) a bug in Chrome, because in Firefox and IE it seems to work OK. Can you check if that's the case for you as well?

Other than that, the only thing I can suggest is to use the WordPress plugin version (not the native JS version), perhaps that will have better results: https://wordpress.org/plugins/sticky-menu-or-anything-on-scroll/

**Comment by MrJoshFisher** [comment]
cheers seems to be ok now, could have been a bug but ill keep it in mind thanks again :+1:
