### ISSUE TITLE
Original menu within a 960px wrapper

### ISSUE THREAD

**Issue by iwanikhalid** [senff/Sticky-Anything#8]
Hi @senff 

Thanks for creating this great plugin. I'm a newbie with jQuery and it's such a relief to be able to do this within minutes using your plugin.

I have a question to ask if you don't mind. If my menu wrapper is within a 960px wrapper, can the cloned menu wrapper be at 100% width?

Or should I place the menu on it's own out of the website wrapper?

Thanks!

**Comment by senff** [comment]
Many apologies for the late response -- I never received a notification of this question!

Is this still an issue that you need help with?

**Comment by iwanikhalid** [comment]
Hi @senff no problem. I managed to figure it out. Thanks for the great plugin! :)
