### ISSUE TITLE
JS is not working on cloned menu

### ISSUE THREAD

**Issue by noizo** [senff/Sticky-Anything#9]
delete….

**Comment by senff** [comment]
I noticed you have it fixed now. Was there anything special you had to do to make it work, or was it a mistake on your end?

**Comment by noizo** [comment]
I had to load a script that was opening fancybox link after menu cloned was generated. I've placed it in footer, and everything worked just fine.

Thanks for concern :)

**Comment by senff** [comment]
Yeah that makes sense! Glad it worked out. :+1:
